### ISSUE TITLE
Add configuration option to exclude samples

### ISSUE THREAD

**Issue by percyfal** [percyfal/snakemake-rules#30]

**Comment by percyfal** [comment]
Add subsections include and exclude; syntax is 

```
samples:
  include:
    - sample1
  exclude:
    - sample2
```
